version: "2"
run:
  timeout: 10m

formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bank-vaults/vault-env)
    goimports:
      local-prefixes:
        - github.com/bank-vaults/vault-env
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: false

linters:
  settings:
    misspell:
      locale: US
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-specific: false # don't require nolint directives to be specific about which linter is being skipped
    revive:
      confidence: 0.1
  enable:
    - bodyclose
    - errcheck
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - unconvert
    - unparam
    - unused
    - whitespace
